// Environment art for Mortars Away: scenery props, sky elements, HUD icons,
// menu furniture and 16x16 tileable terrain surfaces.
// Format matches js/pixelart.js: { w, h, palette, pixels: [rows] }, '.' = transparent.
// Generated pixel data - edit by hand only if you keep row widths exact.

export const ENV_PALETTES = {
  wood: { 'a': '#140e07', 'b': '#2b1f11', 'c': '#3f2e1a', 'd': '#563d22', 'e': '#6f4f2c', 'f': '#8a6b46', 'g': '#b39a6f' },
  pine: { 'a': '#080e0a', 'b': '#122019', 'c': '#1a2f20', 'd': '#244028', 'e': '#2f5231', 'f': '#3d6739', 'g': '#2b1f11', 'h': '#3f2e1a' },
  metal: { 'a': '#0b0c0e', 'b': '#1e2126', 'c': '#33373d', 'd': '#4b5058', 'e': '#666c75', 'f': '#878e98', 'g': '#4a2c14', 'h': '#7a4620', 'i': '#a3612c', 'j': '#c9973c', 'k': '#7d5a1e' },
  sandbag: { 'a': '#120f08', 'b': '#2e2716', 'c': '#453a21', 'd': '#5c4d2c', 'e': '#75633a', 'f': '#8e7a4c' },
  concrete: { 'a': '#0d0e10', 'b': '#26282b', 'c': '#3c3f43', 'd': '#53575c', 'e': '#6a6f75', 'f': '#83888e', 'g': '#2b2415' },
  brick: { 'a': '#120b08', 'b': '#331c14', 'c': '#4d2a1e', 'd': '#663a29', 'e': '#7f4c36', 'f': '#3a342c', 'g': '#57503f', 'h': '#6f6857' },
  flag: { 'a': '#0b0c0e', 'b': '#2b2f35', 'c': '#4b5058', 'd': '#6b727b', 'e': '#4a1f1c', 'f': '#6e2c25', 'g': '#8f3b2e', 'h': '#a9584a' },
  cloud: { 'a': '#6e7681', 'b': '#818994', 'c': '#98a0aa', 'd': '#b3bac2', 'e': '#ccd1d7' },
  hill: { 'a': '#39424c', 'b': '#454f5a', 'c': '#525d68', 'd': '#606b77', 'e': '#6e7986' },
  smoke: { 'a': '#2c3035', 'b': '#3c4148', 'c': '#4e545c', 'd': '#616870' },
  bird: { 'a': '#232a31', 'b': '#3d454e' },
  ui: { 'a': '#080a0d', 'b': '#1b1f25', 'c': '#9aa1ab', 'd': '#e6eaf0', 'e': '#c2c8d0', 'f': '#a83a2c', 'g': '#d0604c', 'h': '#d9a441', 'i': '#8c6a22' },
  tGrass: { 'a': '#0d1208', 'b': '#171f0f', 'c': '#212c16', 'd': '#2b391d', 'e': '#374826', 'f': '#2a2317', 'g': '#191309' },
  tDirt: { 'a': '#1c1409', 'b': '#291d0f', 'c': '#362715', 'd': '#44321b', 'e': '#523d23', 'f': '#634d2e' },
  tClay: { 'a': '#26140a', 'b': '#341b0d', 'c': '#432312', 'd': '#522c18', 'e': '#63371f', 'f': '#744329' },
  tRock: { 'a': '#16181a', 'b': '#212429', 'c': '#2e3238', 'd': '#3c4046', 'e': '#4a4f56', 'f': '#5a6068' },
  tSnow: { 'a': '#6b737c', 'b': '#8b939c', 'c': '#a9b1b9', 'd': '#c4ccd3', 'e': '#dde3e8', 'f': '#4f4a41', 'g': '#63594a' },
  tSand: { 'a': '#5f4f2c', 'b': '#725f38', 'c': '#856f42', 'd': '#98814e', 'e': '#ab935c', 'f': '#bda56b' },
  tAsh: { 'a': '#111113', 'b': '#1c1c1f', 'c': '#28282c', 'd': '#353539', 'e': '#434348', 'f': '#5b4b40', 'g': '#7a3a1c' },
  tMud: { 'a': '#150f09', 'b': '#221a10', 'c': '#2f2416', 'd': '#3c2e1d', 'e': '#4b3b26', 'f': '#5f4d35', 'g': '#75634a' },
};

export const ENV_SPRITES = {
  tree_dead_a: {
    w: 20, h: 34, palette: 'wood',
    pixels: [
      '......afa...........',
      '......afaa..........',
      '......acafa.........',
      '......acfca.........',
      '......abbca.........',
      '......abbda.....aa..',
      '......abccda...affa.',
      '.......abcda...aca..',
      '.......abbda..aba...',
      '.......abcda.aba....',
      '.......abcdaaba.....',
      '.......abbcdcba.....',
      '..aa...abcbcba......',
      '.affa..abcbba.......',
      '..aca..abccda.......',
      '...abaa.abccda......',
      '....abcaabccda......',
      '.....abcabccda......',
      '......abcbccda......',
      '.......abbccda.a....',
      '........abccdaafa...',
      '........abccdaca....',
      '........abbccca.....',
      '.......abcbcda......',
      '.......abcccda......',
      '.......abcbcda......',
      '.......abcccda......',
      '.......abcccda......',
      '.......abcccda......',
      '......abcccccda.....',
      '.....abccccccda.....',
      '....abcccbccccda....',
      '..aabbbccccccdddaa..',
      '.acbbccccccccccddca.',
    ],
  },
  tree_dead_b: {
    w: 16, h: 26, palette: 'wood',
    pixels: [
      '.....a..........',
      '....afa.........',
      '...abfa...aa....',
      '....aca..afba...',
      '.....acaaaca....',
      '.....affffa.....',
      '.....acbcca.....',
      '......abcda.....',
      '......abcda..a..',
      '......abcba.afa.',
      '.....abcccdaaca.',
      '.....abcccdcca..',
      '.....abccccaa...',
      '.....abcccda....',
      '.....abccbda....',
      '.....abcccda....',
      '.....abcccda....',
      '.....abcccda....',
      '.....abccbda....',
      '.....abcccda....',
      '....abccccda....',
      '....abccccda....',
      '...abcccccda....',
      '..abcccccccda...',
      '.abcccccbcccdaa.',
      'acccccccccccccda',
    ],
  },
  tree_pine: {
    w: 22, h: 38, palette: 'pine',
    pixels: [
      '.........ada..........',
      '.........aca..........',
      '.........acda.........',
      '........abcda.........',
      '........abbda.........',
      '.......abbccda........',
      '.......abbccda........',
      '......abbccccda.......',
      '......abbbebbca.......',
      '.......acdddda........',
      '......abbcbccda.......',
      '......abbccccda.......',
      '.....abbbbccccda......',
      '....aabbccccccdaa.....',
      '...abbbbbbebbbbcba....',
      '....aacddddddbdaa.....',
      '....abbccccbceda......',
      '....abbccccccceda.....',
      '....abbcccccbccda.....',
      '...abbccccccccccda....',
      '..abbbbbbebbbbbbcba...',
      '...aacddddddddddaa....',
      '...aabbccccccccda.....',
      '..abbccccbceccccda....',
      '...abbceccccceccda....',
      '..abbccccccccccccda...',
      '.abbbbbbbbbbbbbbbcba..',
      '..aacdddddddedbddaa...',
      '..abbeebcccccccccda...',
      '..abbcccccccbceccda...',
      '.abbbcccceccccccceda..',
      '.abbceccccccccccccdaa.',
      'abbbbbbbbbbbbbbbbbbcba',
      '.aaabbbaabghaabaabaaa.',
      '....aaa.aggha.a..a....',
      '........aggha.........',
      '.......aggggga........',
      '......aggggggga.......',
    ],
  },
  barbwire: {
    w: 24, h: 12, palette: 'metal',
    pixels: [
      '..afda..................',
      '..aefa..................',
      '..affaef.f.........f.fff',
      '..abbfffff...f.f.fffffbb',
      '..aedbbfbffffffffbbfbf..',
      '.eaeda....bbbfbfb....f.f',
      '..afff...f.f....f.f..fff',
      '..abbbfffff.....ffffffbf',
      '..aedabbbfbffffffbfbb...',
      '..affff.f..bfbfb..f.ffff',
      '..abbbfffffffffffffffbbb',
      '..aedafbfbbbfbfbbbfbf...',
    ],
  },
  sandbags: {
    w: 22, h: 12, palette: 'sandbag',
    pixels: [
      '....aeeeeaaeeeea......',
      '...addfdcdddfdcda.....',
      '...addcdcccdddcda.....',
      '..aaabbbbaabbbbaaa....',
      '.aeeeeaaeeeeaaeeeea...',
      'addfdcdddfdcdddfdcda..',
      'addddcdddddcccdddcda..',
      '.abbbbaabbbbaabbbbaaa.',
      'aeeeeaaeeeeaaeeeeaeeea',
      'ddfdcdddfdcdddfdcddfcc',
      'ddddcddcddcdccddcdddcd',
      'abbbbaabbbbaabbbbabbba',
    ],
  },
  crate: {
    w: 14, h: 12, palette: 'wood',
    pixels: [
      '.aaaaaaaaaaaa.',
      'abfbffffffbfba',
      'addcddddedbeda',
      'addbdeddeebdda',
      'accbccccccbcca',
      'addbdddddebdda',
      'addbddbbddcdda',
      'addbddddddbdda',
      'accbccccccbcca',
      'adebddddddbdda',
      'aedbddeeddbdda',
      'abbbbbbbbbbbba',
    ],
  },
  barrel: {
    w: 10, h: 14, palette: 'metal',
    pixels: [
      '..aaaaaa..',
      '.aeeeeeea.',
      'aceeeeeeba',
      'acedddgdba',
      'aceddddhba',
      'acccccccca',
      'acedddddba',
      'acehhdddba',
      'acedidddba',
      'acccccccca',
      'aceddddgba',
      'achdddddba',
      'aceddghdba',
      'acedddddba',
    ],
  },
  wreck_tank: {
    w: 40, h: 22, palette: 'metal',
    pixels: [
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '...........aaaa....a....aaa.............',
      '..........abddbaaaaaaaaabdea............',
      '..........abhaaaaaaaaaaaaaea............',
      '..........agcchccbcbgcccccea............',
      '...aaaaaaaabchcccccccccccceaaaaa........',
      '..abdddhdbbddhbdggdddbddddddddbda.......',
      '..abcgcbcccbbbccccccccccccgcgcbchaaa....',
      '..abcbaabcccccccccccccccbbccbcbccbbba...',
      '..abcgbgbcccccgccccccbhccchcbgbcchbba...',
      '..abcccccccccccccccccchccchcbcbccccda...',
      '..abcchcccccccccccccccccccccccccccccda..',
      '..abbhbbbbbbbbbbbbbbbbbbbgbbbbbbbbbbbba.',
      '..aaaaaaaacccbbbbhccbbbccchgbcbcbbcccba.',
      '.abbccccccccahcbccagcbccaccbchaccccacca.',
      '.agbccagbggcaccbccaccbcgaccbccaccccacca.',
      '.accbbgcbbbcccbbbcccbbbcccbbgchchbcccba.',
      '.abhbbcbbcbbcbbcgbcbbhbbhbbcbbcbbcbbbba.',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
    ],
  },
  bunker: {
    w: 34, h: 20, palette: 'concrete',
    pixels: [
      '..................................',
      '.....aaaaaaaaaaaaaaaaaaaaaaaa.....',
      '....afbffcffffffffffffcffffffa....',
      '....aeeeeceecfeeeeeeeeceffeeea....',
      '...acccccccccccccccccccccccccca...',
      '....aacdbfdddddddddddcddfddcaa....',
      '....accdcdddddddddddddddddddca....',
      '....acddddddddddfdddddddddddca....',
      '....acddbbbbbbbbbbbbbbbbbbddca....',
      '...acdbcaaaaaacaaaacaaaaaadddca...',
      '...acdddaaaaaacaaaacaaaaaadddca...',
      '...acdcdaaaaaacaaaacaaaaaadddcca..',
      '..accddddffcffcfffffcffbfdddddca..',
      '..acccddddddfccdddcddbfdddddddca..',
      '.acfdbdddbfdddbddddbdddddddddcdca.',
      '.acdddddddbdddddcdfddddddddcddcca.',
      '.acddfddddddddddfdddcddddddddbdca.',
      'acddddcddbdcddddddddddddfddddddfca',
      'ggdggggfgdgdgdddbdgdbdggcbdddgffcg',
      'gggggggggggggggggggggggggggggggggg',
    ],
  },
  ruin_wall: {
    w: 26, h: 30, palette: 'brick',
    pixels: [
      '..........................',
      '..........................',
      '....aa....................',
      '...ahha...........aa......',
      '...aheaaaa......aahha.....',
      '...addhhhha....ahhhda.....',
      '...afgffhfa...aahgggaaaa..',
      '..aaddgdddaaaahhddgdhhhha.',
      '.ahhccfccchhhhccccfchccca.',
      '.ahhgggfgfhhhgfggggffggfa.',
      '.acgeeeeegdddddgcccccgcca.',
      '.abfdddddgcccccgbbbbbfbba.',
      '..afggfgggggfgffggfggggfa.',
      '..acccfchhhhhhhhhdgddddda.',
      '.abbbbgbbaaaaaaaccgccccca.',
      '.aggfgggfa.....affggfffga.',
      '.adfeeeeea.....adddddfdda.',
      '.acfddddda.....acccccfcca.',
      '.afgffgffa.....aggfggfga..',
      '.aeeeefdda.....addgdddaa..',
      '.addddfcca.....accfccccca.',
      '.afgfgfggaaaaaaaggffffgga.',
      '.acgccccghggggghgeeeefeea.',
      '.abfbbbbbfcccccgdddddgdda.',
      '.agffgfgffggfgggggfgfffa..',
      '.accccgdddddgcccccgddddda.',
      '.abbbbgcccccgbbbbbfccccca.',
      '.afgfgggffggfggggffggggfa.',
      'adefdddddfcccccgeeeeegccda',
      'bcdgcccccgbbbbbfdddddgbbcb',
    ],
  },
  telegraph: {
    w: 14, h: 40, palette: 'metal',
    pixels: [
      '..............',
      '.......aa.....',
      '......adca....',
      '...a..adba....',
      '..aeaaedcea...',
      '..afaafdcfa...',
      '.addddddddda..',
      '.acccccccccea.',
      '..acaadcacaaa.',
      '...acadcca.aea',
      '....acdca...a.',
      '.....adca.....',
      '.....adca.....',
      '.....adba.....',
      '.....adca.....',
      '.....adca.....',
      '.....adba.....',
      '.....adca.....',
      '.....adba.....',
      '.....adca.....',
      '....adca......',
      '....adba......',
      '....adca......',
      '....adba......',
      '....adca......',
      '....adca......',
      '....adca......',
      '....adca......',
      '....adba......',
      '....adca......',
      '....adba......',
      '....adca......',
      '....adca......',
      '...adca.......',
      '...adca.......',
      '...adca.......',
      '...adca.......',
      '...adca.......',
      '..adddda......',
      '..acccca......',
    ],
  },
  helmet_gnd: {
    w: 10, h: 6, palette: 'metal',
    pixels: [
      '..aeddda..',
      '.adeeddda.',
      '.adddgdba.',
      '.acccccba.',
      'aeddddddba',
      '.abbbbbba.',
    ],
  },
  flag_pole: {
    w: 18, h: 30, palette: 'flag',
    pixels: [
      '..aa..............',
      '.adca.............',
      '.adbaaaaaaaaaaaa..',
      '.acbeegfgfgffffea.',
      '.acbeeffefffffaa..',
      '.acbeeeffffffafea.',
      '.acbeefffeffafea..',
      '.acbeegeffffeaa...',
      '.acbeegfgfeea.....',
      '.acbeeffeaaa......',
      '.acbeeeggea.......',
      '.acbeefffa........',
      '.acbeeffaea.......',
      '.acbaaaa.a........',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      '.acba.............',
      'acccca............',
      'abbbba............',
    ],
  },
  cloud_a: {
    w: 56, h: 18, palette: 'cloud',
    pixels: [
      '........................................................',
      '........................................................',
      '......................eeeeeee...........................',
      '....................eedddddddeeee.......................',
      '..................eeddddcccdcdddde......................',
      '..................ddddcccccbcccddd......................',
      '............eeeeeedccccccccccccccdeee.eee...............',
      '.......eeeeeddddddccccccccdccccccddddedddeee............',
      '......edddddcccccccccccccbcccdccccdccddccdddee..........',
      '.....edcdcbcccbcddcccccddccccccccccdcdccccdcddeee.......',
      '...eedccccccccccccccccccbcccccccccccbcccbcbccddddeee....',
      '...ddcccdcccbdcdcccdccccccccccccdcccccccccccbccddddd....',
      '..edcccccdccccdcccccbcccccdccdcccccccccccbccccdcccccee..',
      'eedcddcccccbcccccccbccbcccccccbccccccdccccccccccccccdd..',
      'ddddcccccccccdcccbccbcccccccccb.cccbcccccccccccccbcccd..',
      '..bbbbbbbccbccbccbccccbbcccccbbcccdccbbcccccbbbccbccbb..',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..',
      '........................................................',
    ],
  },
  cloud_b: {
    w: 40, h: 14, palette: 'cloud',
    pixels: [
      '........................................',
      '........................................',
      '...................eeeeee...............',
      '................eeeddddddee.............',
      '.............e.edddcccdcdddeee..........',
      '........eeeeededcdcccdcccddddde.........',
      '.......edddddcdccccccbcccccbccdeeee.....',
      '.....eeddcbddcccdccccccccccccccddddee...',
      '...eeddcccccccccccdccccccccccccdcdcdd...',
      '..eddcdccbcdcdcccccccccccccccccdccccc...',
      '..dcdcccccccccccccccccccccccdcdcdcccc...',
      '...bbbbcbbbccbbbbcccbcccbccbbccccccbb...',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..',
      '........................................',
    ],
  },
  cloud_c: {
    w: 72, h: 22, palette: 'cloud',
    pixels: [
      '........................................................................',
      '................................ee......................................',
      '..........................eeeeeeddeeeee.................................',
      '.......................eeeddddddcddddddee...............................',
      '.....................eedddddcdbccccdcccddee.............................',
      '.....................ddccdccccdccbcccccdcddee...........................',
      '...................eeddbcccccccccccccccccccdde...eee....................',
      '.............eeeeeeddccccccccccccccccccccccdcdeeedddeeeee...............',
      '.........eeeedddddddcccccccccccccccccbcccccdbcdddbcddddddee.............',
      '.......eeddddcccccdcbcccccccccccccccccccccccccdddccccccdddd.............',
      '......eddbdddccccccccccccccccccccccccdcccccccccccccdccccddce............',
      '.....edcdcccbccccccdccbccccdcccccccccccbcccccccccccccccccccdeeeee.......',
      '....edcccccdcccccccccccccccccccbcccccccccccccccccccccbcccccddddddeee....',
      '..eedccccbcccbccccccccccccccccbccccccdcdcbccccccccccccccccccdcdcdddd....',
      '..ddcdcccccccccccccccdcccccccccccccccbccccccccccccccccccdbcccccccddcee..',
      '.eccccccdccdcbcccccccccbcccbcbdcccccccdcccccccccccccccccccccccccdcccdd..',
      '.dccccccccccccdcccccccccccccccccccccccccccccccccccccccccccccccccccccc...',
      '.dccccccccbcccccbcbccccccccccccccccccccccccccccccccccccddcccccccccc.....',
      '...bcbcddccccccdcdcccccccccccccccdcccccbccccccccbcccccccccccccccc.......',
      '.bbbbbbbbcbbbcbccccbbdcbbccbcbbbbbbcbcbccbcbbbbcbbbcccccccccbbbbccbcbb..',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..',
      '........................................................................',
    ],
  },
  bird_a: {
    w: 7, h: 5, palette: 'bird',
    pixels: [
      '.......',
      'ba...ab',
      '..aba..',
      '...a...',
      '.......',
    ],
  },
  hill_far_a: {
    w: 96, h: 40, palette: 'hill',
    pixels: [
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '.............eeeeeeee..................................................................eeeeeee..',
      '.....eeeeeeeeddddddddeeee.............eeeeeeeee....................................eeeeddddddde.',
      '..eeeddddddddddbbddddddddeeee.....eeeeddddddddde...............................eeeeddddddbddbbde',
      '.eddddaadddddccccccccddddddddeeeeeddddddbddaddddee...........................eeddddddddcccccccdd',
      '.ddddccccacccccccccccccccddddddddddddbcccccccbcddde........................eeddbddacaacccaccbccd',
      '.dbcacccccacccccbcccccaccccccbddddcaccacccccccccddde.....................eeddddccbcccacacccccccc',
      '.bccbbcccccccccccacacccccccccccbcccccccccccccccbcbdde...................eddddcbcccbccbcacccccacc',
      'ecccccccccccccbbbbbbbbcccccccbccccacccccccaccccccccdde................eedddccccccacccacbbbcbabcc',
      'dccccbbbbbbbbbababbbbaabaccccccccbccccbcbbbbbbbcccccdde..............eddaccacccabcbbbbbbabbbbbbc',
      'dcbabbbccbbbbbbbbbabbbcbaaabbccccbbbbcbbbbabbbaccccccddee..........eedddcccccccbcabbbbbbcbbcacbb',
      'bbbbbbbbabbbbbbcabbbbcbabcbbbabbcbbabcbbbbbbbbbbbbccccbdde........eddaccbccccbbbabbbababbbabbbbb',
      'cbbbbbbbbbbbbbbbbbcbcbbcbcbabcbbbcbbbbbbabbbbbbbbcbccccdadeeeeeeeedddccccbcbbbcbbbbbbbbbbbabbbbb',
      'abbbbbbabbbbbbbbbbbbbcbbbbbbbbbbbbabcbbcbcbbbbbcbbbbcccccddddddddddccccccbbbbbbbbbabcbbbabbbbbbb',
      'cbabbbbbbbbbbbcbbbbcbbbbbbbbbbbbabbbbbbabbabbbbbbbbbbbcccaddddddddaccccbbbcbbbabbbbbcbcbbbbbcabb',
      'cbbbbbbcbbbbbbbbbbbbbbbbcbabbbbbbbbbbabbbbabbbbcbcbbbbcccccacccccccbccbbabbcbbbbbbbbbbbbcabbbacb',
      'bbbbcbabbbbbbbcbbbbbbbcbbcbbbbcbbcabbcbbbbbbcbbbbabbbbbacccccccccccacbbbbbbbabbbbbaccbbbbbbbbbbb',
      'bbbbbcbbbbcbcbbbbabbbbbbabbbbbbbbcbbbbbbabbbbbbbbbbbbbbcbcccccbacccbbbcbbbbbbbbbbbbbbbabbbabbbbb',
      'bbbcbbbbbbbbbababbbabbbbcbbbbabbbbbabbbbbbbbaabbbcbbbcbbcbcbcccbccbbbbcbbbbbbbbbbbbbbbbbbbbbabbb',
      'bbbbbbbbbcbbbbcabbcbcbbbbcbbabbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbcabbbbcbbbbbbaabbbbbcbabbbbbaabbcbb',
      'baaaaaaaaaaabaaaaaaaaaaaaaaaaaaabbaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaabbaaaaaaaaaa',
      'aaabaaaaaaaaaabaaaaaaaaaaaaaaaaabaaaaaaaabaaaaaaaaaabaaaaaaaaabaaabaaaaaaaaabaaaaaaaaaaaabababaa',
      'aabaaaaabaaaaaabaaaaaaaaaaabbaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaabaaabaaaaaaaaabbaaabbaaaaaababa',
      'aaaaaaaaaaaabaaaaaaaaaababaabaaaaaaaaaaabbaaaaaaabaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaa',
    ],
  },
  hill_far_b: {
    w: 120, h: 52, palette: 'hill',
    pixels: [
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '........................................................................................................................',
      '.....................................................................................eeeeeeeeee.........................',
      '..................................................................................eeeddddddddddee.......................',
      '...............................................................................eeedddddbadbddddddee.....................',
      '...........................................................................eeeedddadacccaccccccbddde....................',
      '.........................................................................eedddddddcccccccccccccccddde...................',
      '......................................................................eeeddddddbcccccccccccccacccccdde..................',
      '....................................................................eeddddaccccccbccccccccccccccbcccddee................',
      '...................................................................eddaddccccccccccccbbbbbcbbbbacccccddde...............',
      '.................................................................eedbbcccccbcbccccbbabbbabbccabbbcacccbdde..............',
      '................................................................edddcacccccccccbbbbbbbbbbbcbbbcbbbbcccccdde.............',
      '...............................................................eddbccccccbcbabbabbbbabbbbbbbbbbbbbbbcacccdde............',
      '...................eeeeeeeee..................................eddcccabccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccdde...........',
      '................eeedddddddddee...............................edbacccacbcccbbbbabbbcbbbbbbbbbbbbbbabbcbcccccade..........',
      '............eeeeddddddddbdddddee............................eddcccacabbbbbabbbbbbbbbbbbbbbabbbbbbbacbbbbccacadee........',
      '.......eeeeedddddddccacccacbbddde..........................edacccabbbbbbbabbcbbabbcbbbbcbbabcbbbbbbbbbbabccbcddde.......',
      '...eeeedddddadddcaccccabacccccdadee.......................edaccbcbbbbbbbbbbccbbbbcbccbbbbbbbbbbbbbbbbbbccbccccdddee.....',
      '..edddddddddcccccccccccaccccccccddde.....................eddcccacbbbabbbbcbbbcbbbbbbbabbbcabbbabbbbbbbbbabbcccccdddee...',
      '.edaddbccccccacccbccaccccbbcccbccbdde...................eddbccabbbabbbabbbbcbbbbbbbcbbbbbbbbbcbbbbbaabbbbbbbccbbcddddee.',
      '.ddccbcbbccccccccccbbababbbbcccbaccdde.................eddccccbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbccbbcbcbbbbcccccbdddde',
      '.dccccccccccccccbbbbbbbbcbbbbbbcccccddee.............eeddcacbcbacbbccbbbcbcbbbcbbbbbbbbbbbbcbbcbcbbbbbbcbcbbabcccaccaabd',
      'ecccccacccccbbbbbbbbbbbbbbbbbabbcccccddde...........edddbccabbabccbcbbbbbbbbbbbbcbbbbbbbbbbbbccbabbbbbbbbcaabbbbccabcccd',
      'dccaaacbbbbbbbbbbbbcbabbbabbbbbbbcbbccdddee.......eedddccccbbbcbcbbbbbbbbbbbbbbabbbbbbbbbcbbbbcbbbcabbbbaababbcbcccccccc',
      'daabbabbabbbbabbbbbbbbbbbbbababbbbccccccaddeeeeeeeddbcacacbbbbbbbbcbbbbbcbbbbbbbbbbbabbbbbabbbbbbbbbbbcbbbbbbcbcbbbbccca',
      'ccbbbbbbbbbbbbabbbbbbbbbbcbcbbbbbbbbaccccdddddddddddcccccbbbbbbbbbbbbabbbacbcbbbbbbcbbbbacbabbbbbbbbbcbbacbabbccacbabacc',
      'bcbbbbbbbbbcbbbcabbbbbbbbcbbbbbbabbbbbbccacddaddddacbcbcbbbcbcbabbabbbbbcbbbbbabbbbbbbbabbbbbbbbbbbbbbbbbbbbbbcbbbbcbbbc',
      'ccabbbcbbbbbbbbcbabbbcbbbbbbabccbbbbbbaccccccccccbcccccbbbbbbbcbbbbbbbbbcbcbbabbabbbbbbbbbbbcababbbbcbbbbbbbcbcbbbbbbbbb',
      'cbbbbbbbabbbcbbbbbbabbbbababcbbbbbccbabbaccacbccccbcccbbbbbbbbcbbbbccbbccbbbbbbabbcbbbbbbbbbbbcbbbababbbbccbbbbbbcbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbaabbbbbbbbbbcbbababbbcbaacbcacbcbcbcbbbbbbbbbccabbbbcbbcbbbccbbbbbbbbbbbbbbbbcbbbbbbcbabbbbbbbbacbbb',
      'bbcbbbbbabcbbbcbbbbabbbbbbbbbbbcbbbabbbbbbbcccacbcbbbcbbbaabbabbbcbbabbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbabbbbcbbbbcaabbbcbbb',
      'bbbcbbabbbabbbbbbbcbbbcbbbbbbcbbbbbbbbcabbbbbcbbbbbbbbbbabbbbbbbbcbbaabbbabbacbcbbbbbbbbabbaabbbbbbbcbbbcbbcbbbbbbbbbbbb',
      'bbbbbbbbbbaccbbcbbbbbbbbbcbbbbbbcbbbacbbbbccbbabbbbbbbccbbbbbbbbbbbcbbbbbbabbbbbbbabbbbbababcbacbbabbbbbbbbbbbbbbbbbbbbb',
      'babbbbbbbbabbbbbbbbbbbbbcbcbbbcbbbbbbbbbabbbbbbabbbbbbbbbabbbabbbbbbcbbbbbbbbbbabbbbbbbbcbbbbbbbbbbabbbbbbbbbbcbbbbbbbbc',
      'abbbbbcabbcbccbbbabbbbabbbacbbbccbababbcbbbbbcbbbbbbbabbbbccbbbbbbbbcbbbbbbbcbbbccbbabbbbbbbbbbbbbbbabbbbbbbbbbbcbbabbbb',
      'aaaaaaaaaaabaaaabaaabaaaaaaaaaabaaaaaaaaabaaabaaaaaaaaaaaaaaaabaaaaaaaaaabaaaaaaaaaaaaaaaaaababaaaaaaaaaaaabaabbaaabaaaa',
      'abaaaaabaaabbaaaaaaaaaaaabaaaaaaaaababababbbaaaaaaaaaaaaaaaabaaaaaaaaabaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaabaaa',
      'aaaaabaaaaaaaaaaaaaaaabaabaaaaaaabaaabbaaaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaabaaaabaaabb',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaababaabaaaabaaaaaabaaaaaaaaabaaaaaaa',
    ],
  },
  smoke_column: {
    w: 18, h: 48, palette: 'smoke',
    pixels: [
      '....cc..bb...c.cd.',
      '...d....bbb.c.c.d.',
      '.....c.b.b.b......',
      '...c..b.b.b.c.....',
      '..d...bbb.b.c.....',
      '..dc..b.bb....d...',
      '....b.bb..........',
      '..c..bbbbbbc.d....',
      '..c.bbbbbb..c.....',
      '..cbb.bbbbb.......',
      '.dcb.bbbb.........',
      '....b.bb.b........',
      '..cb.bbbbbc.......',
      '....bbab..........',
      '.....aabbb........',
      '....baaabb........',
      '...b.aaa.b........',
      '.dcbb.aabb........',
      '..cb..aa..c.......',
      '...baaaa.b........',
      '...ba.aabbc.......',
      '..c.aaaabbc.......',
      '.....a.a.b........',
      '....baa..b........',
      '....baaaa.........',
      '....baaaabd.......',
      '.....aaa.b........',
      '.....aaaab........',
      '....baaaabd.......',
      '...dbaaaa.........',
      '....baaaab........',
      '.....aaaab........',
      '....baaa..........',
      '.....aaa..........',
      '....caaaa.........',
      '....caaaa.........',
      '....caaab.........',
      '....caaab.........',
      '.....aaa..........',
      '....caaa..........',
      '....caaa..........',
      '.....aa...........',
      '..cbaab...........',
      '..cbaab...........',
      '...baab...........',
      '..cbaab...........',
      '...baab...........',
      '...baab...........',
    ],
  },
  icon_wind: {
    w: 16, h: 16, palette: 'ui',
    pixels: [
      '..........a.....',
      '...aaaaaaada....',
      '..adddddddada...',
      '..aeddddddada...',
      '...aaaaaaada....',
      '..........aa....',
      '..aaaaaaaaada...',
      '.adddddddddada..',
      '.aeddddddddada..',
      '..aaaaaaaaada...',
      '.........a.a....',
      '.....aaaada.....',
      '....addddada....',
      '....aedddada....',
      '.....aaaada.....',
      '.........a......',
    ],
  },
  icon_weight: {
    w: 16, h: 16, palette: 'ui',
    pixels: [
      '................',
      '................',
      '................',
      '......aaaa......',
      '.....adddda.....',
      '....ad....da....',
      '....ad....da....',
      '...aeeeeeeeea...',
      '...adddddddea...',
      '..adddddddddea..',
      '..adddddddddea..',
      '..adddddddddea..',
      '.adddddddddddea.',
      '.adddddddddddea.',
      '..aaaaaaaaaaaa..',
      '................',
    ],
  },
  icon_power: {
    w: 16, h: 16, palette: 'ui',
    pixels: [
      '................',
      '................',
      '................',
      '.a....a....a....',
      'aea..ada..ada...',
      'aeea.adda.adda..',
      '.aeea.adda.adda.',
      '..aeea.adda.adda',
      '..aeea.adda.adda',
      '.aeea.adda.adda.',
      'aeea.adda.adda..',
      'aea..ada..ada...',
      '.a....a....a....',
      '................',
      '................',
      '................',
    ],
  },
  icon_angle: {
    w: 16, h: 16, palette: 'ui',
    pixels: [
      '................',
      '................',
      '.............a..',
      '...........aada.',
      '..........addda.',
      '.........addda..',
      '.......aaddaa...',
      '......adeda.....',
      '.....addea......',
      '...aaddaaea.....',
      '..adddaaaeaaaa..',
      '.adddddddedddda.',
      '.adddddddddddda.',
      '..aaaaaaaaaaaa..',
      '................',
      '................',
    ],
  },
  icon_health: {
    w: 16, h: 16, palette: 'ui',
    pixels: [
      '................',
      '......aaaa......',
      '.....agggga.....',
      '.....aggffa.....',
      '.....agfffa.....',
      '..aaaagfffaaaa..',
      '.agggggfffffffa.',
      '.agfffgfffffffa.',
      '.agfffgfffffffa.',
      '.agfffgfffaaaa..',
      '..aaaagffa......',
      '.....agffa......',
      '.....agffa......',
      '.....agffa......',
      '......aaa.......',
      '................',
    ],
  },
  icon_skull: {
    w: 16, h: 16, palette: 'ui',
    pixels: [
      '................',
      '.....aaaaaaa....',
      '....addddddea...',
      '...adddddddda...',
      '..adddddddddea..',
      '..adaaaddaaaea..',
      '..adaaaddaaaea..',
      '..adaaaddaaaea..',
      '..addddaadddea..',
      '...adddaaddea...',
      '....aeeeeeea....',
      '....adadada.....',
      '....adddddda....',
      '....adadada.....',
      '.....a.a.a......',
      '................',
    ],
  },
  crosshair: {
    w: 15, h: 15, palette: 'ui',
    pixels: [
      '......ada......',
      '.....aadaa.....',
      '....addedda....',
      '...adaaaaada...',
      '..ada.aea.ada..',
      '.ada...a...ada.',
      'aadaa.....aadaa',
      'ddeaea...aeaedd',
      'aadaa.....aadaa',
      '.ada...a...ada.',
      '..ada.aea.ada..',
      '...adaaaaada...',
      '....addedda....',
      '.....aadaa.....',
      '......ada......',
    ],
  },
  banner_left: {
    w: 16, h: 24, palette: 'metal',
    pixels: [
      '.aafaa..........',
      'aeejeea.........',
      'aejjjea.........',
      'aeejeea.........',
      '.aeecaaaaaa.....',
      '.aedcddjddda....',
      '.aedcaaaaaafa...',
      '.aedca.....ada..',
      '.aekca......ada.',
      '.aedca......aea.',
      '.aedcaaaaaaaea..',
      '.aedceeeeejaa...',
      '.aedcdddddkaa...',
      '.aedcaaaaaaaea..',
      '.aedca......aea.',
      '.aekca......ada.',
      '.aedca.....ada..',
      '.aedcaaaaaafa...',
      '.aedcddjddda....',
      '.aeecaaaaaa.....',
      'aeejeea.........',
      'aejjjea.........',
      'aeejeea.........',
      '.aafaa..........',
    ],
  },
  banner_right: {
    w: 16, h: 24, palette: 'metal',
    pixels: [
      '..........aafaa.',
      '.........aeejeea',
      '.........aejjjea',
      '.........aeejeea',
      '.....aaaaaaceea.',
      '....adddjddcdea.',
      '...afaaaaaacdea.',
      '..ada.....acdea.',
      '.ada......ackea.',
      '.aea......acdea.',
      '..aeaaaaaaacdea.',
      '...aajeeeeecdea.',
      '...aakdddddcdea.',
      '..aeaaaaaaacdea.',
      '.aea......acdea.',
      '.ada......ackea.',
      '..ada.....acdea.',
      '...afaaaaaacdea.',
      '....adddjddcdea.',
      '.....aaaaaaceea.',
      '.........aeejeea',
      '.........aejjjea',
      '.........aeejeea',
      '..........aafaa.',
    ],
  },
  rivet: {
    w: 6, h: 6, palette: 'metal',
    pixels: [
      '..aa..',
      '.afda.',
      'afedda',
      'addcba',
      '.adba.',
      '..aa..',
    ],
  },
  tile_grass: {
    w: 16, h: 16, palette: 'tGrass',
    pixels: [
      'ccceecccbccegccc',
      'ecedegfffbfccgcc',
      'ccgceccebbbccccc',
      'dceebbbebbebbccc',
      'decebbgbbffeebcg',
      'cccbbebbbbbfgfcc',
      'cccbbbccccceecfc',
      'ccbbbecddddcccfc',
      'ccebbccdddddccgc',
      'ccgbbccddddeccce',
      'eccgcccfffcececc',
      'ccccccccccfebbcc',
      'cccccfccbfebbbee',
      'ccccccccbbbbbccc',
      'cccddcccbbcfcccc',
      'cccddcccbbcccgcc',
    ],
  },
  tile_dirt: {
    w: 16, h: 16, palette: 'tDirt',
    pixels: [
      'decceccdadbbdbaa',
      'ddeccccbbbdcbddd',
      'ddcccccdddcccccd',
      'ddccbccaddcfcfcd',
      'edccbccaddacaccd',
      'ddccbcccdcecbccd',
      'ddccfccccccccccd',
      'deccbccccccecccd',
      'ddcccccccccccacd',
      'dccccccccccacccd',
      'cccccccccccfccce',
      'cccccccaedecaccc',
      'ccccccaedddeccac',
      'ccbbceadfdadecbb',
      'bbcccccddddbbbdd',
      'ddcccccddddedddd',
    ],
  },
  tile_clay: {
    w: 16, h: 16, palette: 'tClay',
    pixels: [
      'ccbbfcdddddaaaaa',
      'aaaeecedfdddddca',
      'cefcccdeeddddccc',
      'ccccccddddbeccce',
      'ccccccdbdddccccc',
      'cccccfcbddcccbcc',
      'bbcccccccccccccb',
      'bfbccccccccccbcb',
      'bbbceccccccfcccb',
      'bbbeeecccccccccb',
      'ebbccccceeccccbe',
      'bbbcccccfceeeeeb',
      'bbbccccccccccbbb',
      'bbbccccccccfccbb',
      'bbbcccdddddddccb',
      'bbfbccddddbddfcc',
    ],
  },
  tile_rock: {
    w: 16, h: 16, palette: 'tRock',
    pixels: [
      'ddddeaaaacddddfd',
      'ddddccccccdddddd',
      'dddddaacccccdddd',
      'ddddecccccccccad',
      'aaafddcccccccada',
      'ddaeccccfcccccde',
      'dfaccccccccccfdd',
      'dcafbbbccccddded',
      'dcabbbbccccedddd',
      'dcabbbbccccddadd',
      'ddeabbcccccdddad',
      'ddacbbcccccddadd',
      'ddacbbaccfceaadd',
      'dddcbccaaeaddadd',
      'dddcccccccdddddd',
      'ddddaccccaaddddd',
    ],
  },
  tile_snow: {
    w: 16, h: 16, palette: 'tSnow',
    pixels: [
      'bdddddageeeeeebb',
      'ddddddgdeeeebbfd',
      'ddeedgebbbeebedd',
      'dddeeeeeeebaefdd',
      'bddeeeeeeaeebbda',
      'dbdeeeeeegedddbg',
      'dedeeeeeedddeade',
      'dddeeeeddddddeed',
      'dadeeedddddffadd',
      'dddddddeeddddddd',
      'eddddedefeedddde',
      'eedddddeeeeeeeee',
      'eaeddddeeeeeeeee',
      'eedddddeeefgeeee',
      'eddddddeeeeafege',
      'dbbbddddgeeegeed',
    ],
  },
  tile_sand: {
    w: 16, h: 16, palette: 'tSand',
    pixels: [
      'eafcccbcdcfeccbc',
      'cfcccecddfcccbcc',
      'fdccbcddfddcbccd',
      'ddcbccfeeddbccff',
      'ddbccffeeeeecffd',
      'dbccefdeebddffed',
      'bccffedbbddffdeb',
      'ccffdabdddffddbc',
      'cffddbdddffeeadc',
      'ffcdbdddafddeadc',
      'cccbcdafdddbdddf',
      'cabcccfdddbdddfc',
      'cecccfddebdddfac',
      'bcccfccdbdddfccc',
      'accabccbeadfcccb',
      'cefccebddffccebc',
    ],
  },
  tile_ash: {
    w: 16, h: 16, palette: 'tAsh',
    pixels: [
      'bbccacaacccccece',
      'aaaacacdadcccccb',
      'bccacdddeddccccc',
      'eccaddddddddccca',
      'cacddeddedgdcccc',
      'cccdddddfdddccgc',
      'ccccccdadddfcccc',
      'cccafecfddcccccc',
      'cccbbcccccccaccc',
      'ccccbcccccfceccc',
      'decccccccdddaddd',
      'dddcaccccddddddd',
      'deedcaaccdadeddd',
      'dddccccaacdddddd',
      'cccccccccaaddddd',
      'cccccccccccacccc',
    ],
  },
  tile_mud: {
    w: 16, h: 16, palette: 'tMud',
    pixels: [
      'bbccacbbbbbbbbbb',
      'abccgcbbbaaaabaa',
      'caccbbbbbbbbcacg',
      'cbcbbbbbgbbccccg',
      'dccgbbbbabcadagd',
      'ddcgbbbbbaacadda',
      'adccbbbbbbccdddd',
      'dadcccbbbbcccddd',
      'bddcgccbbcccgded',
      'dddccebbbbcccdde',
      'beeeebbbbbcccddd',
      'ddcgbbbbbbcceedd',
      'dccbbbbbbeeecbgd',
      'cccbbgbbbbbccccc',
      'bacccbbbbbbbbccc',
      'bbaaccbbbbbbgbaa',
    ],
  },
};
