// Mortars Away - pixel art data for units, projectiles and effects.
// Generated art data: string grids + indexed palettes, consumed by js/pixelart.js.
// The key "." is always transparent and never appears in a palette.
// Sprites face RIGHT; the renderer mirrors them for the left-hand player.
// mortarBarrel_* is the tube only, drawn horizontal, pivot at pixel (3, 4).

export const UNIT_PALETTES = {
  mortarAllied: { 'a': '#12150e', 'b': '#333a1f', 'c': '#4a5528', 'd': '#8a9450', 'e': '#8a7f52', 'f': '#a89a6b', 'g': '#2a2620', 'h': '#46403a', 'i': '#6b6156', 'j': '#59401f' },
  mortarAxis: { 'a': '#0e1113', 'b': '#262d2c', 'c': '#38443f', 'd': '#6a7770', 'e': '#6e6a58', 'f': '#8a8672', 'g': '#1b2026', 'h': '#333c44', 'i': '#566370', 'j': '#3d352a' },
  crewAllied: { 'a': '#0b0d07', 'b': '#2f3a1c', 'c': '#4d5c28', 'd': '#74854a', 'e': '#8f9455', 'f': '#c08a5e', 'g': '#8a5c37', 'h': '#1a1409', 'i': '#c9bb7f', 'j': '#a83424' },
  crewAxis: { 'a': '#080a0a', 'b': '#232b28', 'c': '#3d4a44', 'd': '#63706a', 'e': '#7b8880', 'f': '#c08a5e', 'g': '#8a5c37', 'h': '#14161a', 'i': '#6b5636', 'j': '#a02f1e' },
  shellLight: { 'a': '#12141a', 'b': '#4a5058', 'c': '#79818a', 'd': '#9aa2aa', 'e': '#c4cbd1', 'f': '#8f3a24', 'g': '#3a3f46' },
  shellMedium: { 'a': '#101410', 'b': '#3d4a34', 'c': '#5d6b4b', 'd': '#7d8b63', 'e': '#a2ae86', 'f': '#8a5a1e', 'g': '#2b3327' },
  shellHeavy: { 'a': '#0b0d10', 'b': '#2c3138', 'c': '#454c55', 'd': '#606772', 'e': '#7e8792', 'f': '#6b3a1c', 'g': '#20242a', 'h': '#d8b23a' },
  boom: { 'a': '#fff8e0', 'b': '#ffe266', 'c': '#ffbb2e', 'd': '#ff8a18', 'e': '#ef5b12', 'f': '#c23a12', 'g': '#8a2a12', 'h': '#35302c', 'i': '#565049', 'j': '#7a726a', 'k': '#989087', 'l': '#4a3520' },
  flash: { 'a': '#fffbe8', 'b': '#ffe066', 'c': '#ffab2e', 'd': '#ef6d18', 'e': '#b83a10', 'f': '#6e2a12' },
  chip: { 'a': '#241809', 'b': '#5a3f22', 'c': '#836035', 'd': '#a07a45' },
};

export const UNIT_SPRITES = {
  mortarBase_allied: {
    w: 26, h: 14,
    palette: 'mortarAllied',
    pixels: [
      "..........................",
      "............aaaa..........",
      "...........acddba.........",
      "...........acddca.........",
      "...........acccca.........",
      "...........abccbia........",
      "...........ahhaahia.......",
      ".aaaaaa...ahha..ahia......",
      "affffffa..ahha...ahia.....",
      "aeeebeea.ahhaaaaaaahia....",
      "fffffffa.ahggggggggghia...",
      "eeebeeeaagggaaaaaaaagggaa.",
      "fffffffaaiiihiiiiihiiihiia",
      "eeebeeeaaggggjggggggjgggga",
    ],
  },
  mortarBase_axis: {
    w: 26, h: 14,
    palette: 'mortarAxis',
    pixels: [
      "..........................",
      "............aaaa..........",
      "...........acddba.........",
      "...........acddca.........",
      "...........acccca.........",
      "...........abccbia........",
      "...........ahhaahia.......",
      ".aaaaaa...ahha..ahia......",
      "affffffa..ahha...ahia.....",
      "aeeebeea.ahhaaaaaaahia....",
      "fffffffa.ahggggggggghia...",
      "eeebeeeaagggaaaaaaaagggaa.",
      "fffffffaaiiihiiiiihiiihiia",
      "eeebeeeaaggggjggggggjgggga",
    ],
  },
  mortarBarrel_allied: {
    w: 28, h: 8,
    palette: 'mortarAllied',
    pixels: [
      "............................",
      "aaaaaa...................aaa",
      "aghhhaaaaaaaaaaaaaaaaaaaaaha",
      "aghihiiddiiiiiiiiiiiiiiiiiha",
      "aghhhhhhddhhhhhhhhhhhhhhhhga",
      "agggggggddgggggggggggggggga.",
      "aggggaaaaaaaaaaaaaaaaaaaagga",
      "aaaaaa...................aaa",
    ],
  },
  mortarBarrel_axis: {
    w: 28, h: 8,
    palette: 'mortarAxis',
    pixels: [
      "............................",
      "aaaaaa...................aaa",
      "aghhhaaaaaaaaaaaaaaaaaaaaaha",
      "aghihiiddiiiiiiiiiiiiiiiiiha",
      "aghhhhhhddhhhhhhhhhhhhhhhhga",
      "agggggggddgggggggggggggggga.",
      "aggggaaaaaaaaaaaaaaaaaaaagga",
      "aaaaaa...................aaa",
    ],
  },
  crew_allied_idle: {
    w: 12, h: 16,
    palette: 'crewAllied',
    pixels: [
      "............",
      ".....aaa....",
      "....aeeea...",
      "...aeeeeea..",
      "..aaeeeeeaa.",
      "....agffa...",
      "...abcffa...",
      "..abcccda...",
      "..abciicda..",
      "..abccccdd..",
      "..abccccdc..",
      "..abbcccda..",
      "..abb.ccda..",
      "..abb..cda..",
      "..abb..bca..",
      ".ahhh.ahha..",
    ],
  },
  crew_axis_idle: {
    w: 12, h: 16,
    palette: 'crewAxis',
    pixels: [
      "............",
      ".....aaa....",
      "....aeeea...",
      "...aeeeeea..",
      "..aeeeeeeea.",
      "..aaeegffa..",
      "...abcffa...",
      "..abcccda...",
      "..abciicda..",
      "..abccccdd..",
      "..abccccdc..",
      "..abbcccda..",
      "..abb.ccda..",
      "..abb..cda..",
      "..abb..bca..",
      ".ahhh.ahha..",
    ],
  },
  crew_allied_hit: {
    w: 12, h: 16,
    palette: 'crewAllied',
    pixels: [
      "..........a.",
      "...aaa....a.",
      "..aeeea..ada",
      ".aeeeeea.ada",
      "aaeeeeeaada.",
      "..agffa.da..",
      ".abcffada...",
      ".abcccda....",
      ".abcjicd....",
      ".abccccd....",
      ".abcccda....",
      ".abbccda....",
      ".abb.ccda...",
      "aab...ccda..",
      "ahh....bca..",
      "ahhh...ahha.",
    ],
  },
  crew_axis_hit: {
    w: 12, h: 16,
    palette: 'crewAxis',
    pixels: [
      "..........a.",
      "...aaa....a.",
      "..aeeea..ada",
      ".aeeeeea.ada",
      "aaeeeeeaada.",
      ".aaeegffada.",
      ".abcffada...",
      ".abcccda....",
      ".abcjicd....",
      ".abccccd....",
      ".abcccda....",
      ".abbccda....",
      ".abb.ccda...",
      "aab...ccda..",
      "ahh....bca..",
      "ahhh...ahha.",
    ],
  },
  shell_light: {
    w: 10, h: 14,
    palette: 'shellLight',
    pixels: [
      "....aa....",
      "...adda...",
      "..adccda..",
      "..aeccba..",
      "..aeccba..",
      "..affffa..",
      "..aeccba..",
      "..aeccba..",
      "..aeccba..",
      "..aeccba..",
      "..adccda..",
      ".agaccaga.",
      ".ag.cc.ga.",
      ".a..aa..a.",
    ],
  },
  shell_medium: {
    w: 12, h: 18,
    palette: 'shellMedium',
    pixels: [
      ".....aa.....",
      "....adda....",
      "...adccda...",
      "..adccccda..",
      "..aeccccba..",
      "..aeccccba..",
      "..affffffa..",
      "..aeccccba..",
      "..aeccccba..",
      "..aeccccba..",
      "..aeccccba..",
      "..aeccccba..",
      "..aeccccba..",
      "..adccccda..",
      ".agaccccaga.",
      ".ag.acca.ga.",
      ".ag..aa..ga.",
      ".a...aa...a.",
    ],
  },
  shell_heavy: {
    w: 14, h: 22,
    palette: 'shellHeavy',
    pixels: [
      "......aa......",
      ".....adda.....",
      "....adccda....",
      "...adccccda...",
      "..adccccccda..",
      "..aeccccccba..",
      "..aeccccccba..",
      "..ahhhhhhhha..",
      "..ahhhhhhhha..",
      "..aeccccccba..",
      "..aeccccccba..",
      "..aeccccccba..",
      "..aeccccccba..",
      "..affffffffa..",
      "..aeccccccba..",
      "..aeccccccba..",
      "..aeccccccba..",
      "..adccccccda..",
      ".agadccccdaga.",
      ".aga.cccc.aga.",
      ".ag..acca..ga.",
      ".a....aa....a.",
    ],
  },
  boom_0: {
    w: 64, h: 64,
    palette: 'boom',
    pixels: [
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "......................dddd......................................",
      "......................dddbddd...................................",
      "......................dddbdcdd........cc........................",
      ".......................dcccdddd....d..cc...d....................",
      ".......................dccccccdd.dddd....dddd...................",
      ".......................dcccccccdddddddddbbddd...................",
      ".......................ddccccccddcccddddcbbdd...................",
      ".................ddddddddcbbbbcccccccccccbbdd...................",
      "................ddddddddcccbbbbcccccccccccdcdd..................",
      "...............dddddcccccccbbbbbbbbcbbbccccdddd.................",
      "..............dddddccccccccbbbbbbbbbbbbccccdddd.................",
      ".............ddddccccccbbbbbbaabbbbbbbbbccccdddd................",
      "..............dddcccccbbbbbbbaaaaaaabbbbbccccddd................",
      "...............dddcccbbbbbbaaaaaaaaaabbbbccccddd................",
      ".................ddcccbbbbaaaaaaaaaaabbbbcccddd.................",
      ".................dddcccbbbbaaaaaaaaaabbbbcccddd.................",
      ".................dddcccbbbbaaaaaaaaaabbbbcccddd.................",
      ".................dddccccbbbaaaaaaaaaabbbbcccddd.................",
      ".................dbdccccbbbbbaaaaaabbbbbbccccddd................",
      "..................dddccccbbbbaaaaabbbbcccccccddd................",
      "..................ddddcccccbbbbaabbbbccccddddddd................",
      "...................dddddcccbbbbbbbbbcccdddbb....................",
      "....................dddddcccbbbbbbccccddddbb....................",
      ".......................dddccccbbbccccdddd.......................",
      ".......................dddcccccbbccccdd.........................",
      "........................ddddccccccddddd.......cc................",
      ".........................dddddccccdddd..........................",
      "..........................dddddccdd.......cc....................",
      "............................ddddcd........cc....................",
      "..............................dddd..............................",
      "..............................ddd...............................",
      "...............................dd...............................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
    ],
  },
  boom_1: {
    w: 64, h: 64,
    palette: 'boom',
    pixels: [
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "...........................l.....dd..llc........................",
      ".........................e.l.....c...ll.........................",
      "................................dd..c.c.........................",
      "..........................ece...dd....c.........................",
      "........................eeeeee..c...c...........................",
      "........................eeeeeee.c...............................",
      "........................eeeeeeeee...............................",
      "........................eeddeeeeeeeeee..........................",
      ".......................eeedddeeeeeeeeeeeeee.....................",
      ".......................eeeddddeeeeeeeeeeeeeeee..................",
      "............d.eee.......eeddddddeeeeeeeeeeeeeee.................",
      "............dceeeeeeee.eeeddddddddeeeeeeeeeeeee.................",
      "..............eeeeeeeeeeeddddddddddddddeeeeeeeee................",
      "...........cc.eeeeeeeeeeeddcccdddddddddddddeeeee................",
      "............c.eeeedddeeedddccccdddddddddddddeeee................",
      ".............ceeeedddddddddccccccdddddddddddeeee................",
      "..............eeeedddddddddccccccccccdddddddeeee................",
      "..............eeeedddddddddcccccccccccccddddeeeee...............",
      ".....lldc.....eeeedddccccccccbbccccccccccddddeeee...............",
      "........cc.e..eeedddddcccccccbbbcccccccccddddeeeee..............",
      "..........eeeeeeedddddcccccccbbbbbbbcccccddddeeeee..............",
      "........eeeeeeeedddddccccbbcbbbbbbbbbbccccddddeeee..............",
      "..........eeeeddddddcccccbbbbbbbbbbbbbccccddddeee...............",
      ".......e.eeeeddddddccccccbbbbbaabbbbbbccccddddeee...............",
      ".......e.eeeddddddccccccbbbbabaaaaabbbbccccdddeeee..............",
      "......eeeeeedddddccccccbbbbbaaaaaaabbbbccccdddeeeee.............",
      "......eeeeeedddddcccccbbbbbbaaaaaaaabbbccccddddeeee.............",
      "......eeeeeedddddcccccbbbbbaaaaaaaaabbbccccddddeeee..c.c.d......",
      "........eeeedddddcccccbbbbbaaaaaaaaabbbccccddddeeee......d......",
      "........eeeedddddcccccbbbbbaaaaaaaabbbbccccdddeeeee.............",
      "......eeeeeeddddccccccbbbbbbaaaaaaabbbbcccddddeeeec.c.cc........",
      "......eeccedddddcccccccbbbbbbaaaaaabbcccccddddeeee..............",
      "......eeeeedddddccccccccbbbbbaaabbbbbccccdddddeeee..............",
      "......eeeeedddddddcccccccbbbbbbbbbbbbbccdddddeeeee..............",
      ".....eeeeeeddddddddcccccccbbbbbbbbbbbcccddddeeeeee.......c.c....",
      ".....eeeeeeeeedddddddcccccbbbbbbbbbbbcccdddeeeeee...........c...",
      "......eeeeeeeeedddddddccccbbbbbcccbcccccdddeeee.................",
      "........eeeeeeeeddddddccccbbbbccccccccccdddeee..................",
      "............eeeeeeddddccccccccccccccccccdddeee..................",
      "............eeeeeeedddcccccccccccccccccddddeee..........c.......",
      "............ee.eeeedddcccccccccdddcccddddddeee............cl....",
      "................eeedddccccccccdddddddddddddeee..................",
      "...............eeeedddcccccccddddddddddddddeeec.................",
      "...............eeeeddddccddddddddeddddddddeeee..................",
      "...............e.eedddddddddddddeeeddddeeeeee.ell...............",
      "...............e.eeddddddddddddeeeeedeeeeeeee...................",
      "...............e.eeddddddddddeeeee.eeeeeeeee....................",
      "...............e.eedddddddddeeeeee.ceeeeeeee....................",
      "...............eeeedddddeeeeeeee...eeeeeee......................",
      "...............eeeeeeeeeeeeeeee....c..ee........................",
      "................eeeeeeeeeeeeee.....dde..........................",
      "................eeeeeeeeee.ce...................................",
      "...............eeeeee.ee..ec....................................",
      "................eeee..ee...c....................................",
      "................eeee......ll....................................",
      "..........................ll....................................",
      "................................................................",
      "................................................................",
      "................................................................",
      "................................................................",
    ],
  },
  boom_2: {
    w: 64, h: 64,
    palette: 'boom',
    pixels: [
      "........................iiiiiiiii.ff..ff..fff...................",
      ".......................fiiiiiiiiiiffffff..fff...................",
      ".......................iiggiiiiiiieeefff.ggf....................",
      ".......................iiggiiiiieeeeeeeffggf....................",
      ".......................iiiiiiieeeeeeeeeeff....f.................",
      ".....................lfiiiiilleeeeeeeeeeeff...f.................",
      "...........iiii....d.lffiieeeeeeeeeeeeeeeeff..ff................",
      "...........iiiii.....ddffeeeeeeeeeeeeeeeeeef..ff..iiii..........",
      "..........iiiiii....l.fffeeeeeeeeeeeeeeeeeefffff.iiiiii.........",
      "..........iigiii.....lfffeeeeeeedddddeeeeeeeffff.iiiiii.........",
      "..........iiiiii......ffeeeeeeedddddddeeeeeeff..iiiiiii.........",
      "......iiiiiiiii.......ffeeeeeddddddddddeeeeeef...iiiiiiiii......",
      "...iiiiiii..iiiff.....ffeeedddddddddddddeeeeefff.iiiiiiii.......",
      "...iiiiiidi.ffffffffffffeeddddddddddddddeeeeefff.iiiiiiiii......",
      "...iiiiiidiiifffffffffffeedddddddddddddddeeeef..iiiiiiiiiii.....",
      "...iiiiiiiiiifeeefffffffeeddddddddddddddddeeee...iiiiiiiiiii....",
      "...iiiiiiiiieeeeeeeeffffeedddddcccccddddddeeeeff.iiiiiiiiiiii...",
      "...iiiiiiiieeeeeeeeeeeeeeedddccccccccdddddeeeeff.iiiiiiiiiii....",
      "....iiiiiiieeeeeeeeeeeeeeeddccccccccccddddeeefff..iiiiiiiii.....",
      "....fiiiiieeeeeeedddddeeeeddccccccccccdddddeefffffiiiiddli......",
      "...fffiiifeeeeeeddddddddddddcccccccccccdddeeeffffffiiiddl.......",
      "...ffffffeeeeeeeddddddddddddcccccccccccdddeeefffffffffi.........",
      "..fffffffeeeeeedddddddddddddccccbbcccccdddeeeeeeefffff..........",
      "..fffffffeeeeeeddddddcccccdcccbbbbbccccdddeeeeeeefffff..........",
      ".fffff.feeeeeeddddddccccccccccbbbbbbcccddddddeeeeeffff..........",
      ".ffiiiffeeeeeeddddddcccccccccbbbbbbbcccdddddddeeeeffff..........",
      ".f.iiifeeeeeeddddddccccccccccbbbbbbbcccccdddddeeeeefffff........",
      "iiiiiiieeeeeeddddddccccccbbbbbbbbbbbccccccddddeeeeeeffff........",
      "iiiiiieeeeeeeddddddccccccbbbbbbaaabbccccccdddddeeeeeefffff.ll...",
      "iiiiiieeeeeeddddddccccccbbbbbabaaabbbbcccccdddddeeeeeeffff......",
      "iiiiilleeeeeddddddccccccbbbbbaaaaabbbbccccccdddddeeeeef.ffff....",
      "iiiiieeeeeeddddddccccccbbbbbaaaaaaabbbbcccccddddddeeeeefffff....",
      "fiiieeeeeedddddddccccccbbbbbaaaaaaabbbbcccccdddddeeeeeefffff....",
      "fiiieeeeeeddddddccccccbbbbbaaaaaaaabbbbcccccdddddeeeeef.ffff....",
      "ffieeeeeeeddddddccccccbbbbbbaaaaaabbbbcccccdddddeeeeefffff.l.lg.",
      "fffeeeeeeddddddcccccccbbbbbbbaaaaabbbbcccccdddddeeeeefffff......",
      "fffeeeeeeddddddccccccccbbbbbbbbbbbbbccccccdddddeeeeef.ff........",
      "ffeeeeeedddddddcccccccccbbbbbbbbbbbbccccccdddddeeeeef.ff.g......",
      "feeegeeeddddddddcccccccccbbbbbbbbbbbcccccddddddeeeef..fffg......",
      "feeeeeeedddddddddcccccccccbbbbbbbbbbcccdddddddeeeeef..ff........",
      "feeeeeddedddddddddcccccccccbcccccbbccccdddddddeeeeefff..........",
      "feeeeeeeeedddddddddccccccccccccccccccccdddddeeeeeeefff..........",
      "ffeeeeeeeeedddddddddcccccccccccccccccccdddeeeeeeeef...ff........",
      "fffeeeeeeeedddddddddddcccccccccccccccccddeeeeeeeeff...f.........",
      "..feeeeeeeeeddddddddddccccccccccccccccdddeeeeeefff..fff.........",
      "..ffeeeeleeeeedddddddddccccdccccccccccdddeeeefffff..ff..........",
      "ff.ffeeeeeeeeeeddddddddddddddddddddcccdddeeeffff..fff...........",
      "ff..ffeeeeeeeeeedddddddddddddddddddddddddeeeffff..f.............",
      "ffffffleeeeeeeeeeedddddddddddddddddddddddeeef.fff...............",
      "ffffffffeeeeeeeeeedddddddddddddddddddddddeeef.ff................",
      "ff..ffffffeeeeeeeeeddddddddddddddddddddddeeef...................",
      "ff..fffffffeeeeeeeedddddeeeeddddeeddddddeeeef...................",
      ".fffffffffffeeeeeeeeeeeeeeeeeeeeeeeeddddeeeefff.................",
      "..ffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefff.................",
      "...f..ffffff.feeeeeeeeeeeeeeeeeeeeeeeeeeeeeefdd.................",
      "......ffffff.ffeeeeddeeeeeeeeeeeeeeeeeeeeeeffdd.................",
      "........fffffffeeelddeeffeeeeeeeeeeeeeeeeeef..f.................",
      "........ffffffffeellffffffffeffffffeeeeeeeef..f.................",
      ".........ffffffffffffffffggfffffff.ffeeeeef.....................",
      "..........ffffffffffffffff....ffff..fffeeff.....................",
      "..........ff....ffffffff......ffffff..ffff..fff.................",
      "...........f....ffffffff......ffffff....ff..ff..................",
      "...........fffff....f..fffffffffffffff..ff..ff..................",
      "............ffff..........ffffff...fff..ff..ff..................",
    ],
  },
  boom_3: {
    w: 64, h: 64,
    palette: 'boom',
    pixels: [
      ".....................i..iiiiiiii................................",
      ".....................i.iiiijjjii................................",
      "....................ii.iiijjjjjii...............................",
      "............jjjjjj..ii.iijjjjjjjji..............................",
      "............jjjjjj..iiiiijjjjjjjji............iii...............",
      "...........jjjjjjjjiiiiiijjjjjjjji.......i..iiiiiiiiii..........",
      "..........jjjjjjjjjjjihhhjjjjjjjjj..iiii..iiiiii....ii..........",
      "..........jjjjjjjjjjjihhhhjjjjjjj.iiiiii..iiiiii....ii..........",
      "..........jjjjjjjjjjj.hhhhjjjjjjiiiiiiiii.iiii..ii..iiiii.......",
      ".........ijjjjjjjjj...hhhgggjjjh.iiiiiiii.hhhh..iii.iiiii.......",
      ".......i..jjjjjjjjji..hhhgggghhhhiiiiiiiii..hhhiiiiii.ii........",
      "......ii..ijjjjjjjii..hhggggggghhiiiiiiiii..hhiiiiiii.ii........",
      ".....iii....illjjh..hhhhggggggggiiiiiiiiiihh..iiiiiiiiii........",
      "...iiiiigg..hllhhh..hhhhggffggggiiiiiiiiiiggghiiiiiiiiii........",
      "..ii....gg..hhhh..hh..hg..ffff..giiiiiiii.ggggiiiiiiiiii..ii....",
      ".iii........hhhh..hhhhgg..fffff.giiiiiiii.ggggiiiiiiiiii..ii....",
      "..iiiiii..hhhhhhhg..gggg.ffffffffgiigggigggggggiiiiiihhi..iiiiii",
      "..iiiihh..hhhhhggg..gggg.fffefffffggfffffffffggggghhhhhhiiiiiiii",
      "..........hh..gggg..gggffffeeeefffffffffffffff..gg..hhhiiiiiiiii",
      "..........hh..gggg..fffffffeeeeeffffffffffffff..gg..hhhiiiiiiiii",
      "iiijjgghhhhggggggfffffffffeeeeeeeffeeeeeeefffffg..gghhiiiiiiiiii",
      "iijjjgghhhggggggfffffffffeeeedeeeeeeeeeeeeeffffg..gggiiiiiiiiiii",
      "iijjjjjjhhgg..gffffffeeeeeeeddddeeeeeeeeeeeffffffggggiiiiiiiiiii",
      "iigjjjjjhggg..ffffffeeeeeeeedddddeeddddeeeeeffffffggggiiiiiiiiii",
      "iijjjjjhhggggffffffeeeeeeeddddddddddddddeeeeeffffffgggiiiiiiiii.",
      "ighjjjhhgggggfffffeeeeeeddddddcdddddddddeeeeeeffffffggiiiiiiiii.",
      ".g.l...hggggfffffeeeeeddddddddccdddddddddeeeeeefffffgggiiiiiiihi",
      ".......hggggfffffeeeeedddddccccccccccddddddeeeeefffffgggghhh..hi",
      "ii....hhggggffffeeeeedddddccccccccccccdddddeeeeefffffgggghllhh..",
      "ii....hhggggffffeeeeeddddccccccbbbcccccdddddeeeefffffgggghllhh..",
      "iiihhhhhggggfffffeeeeddddccccbbbbbbccccdddddeeeeffffgg..ghhhhhhi",
      "iiiihhhhhggggffffeeeeddddcccbbbbbbbbcccdddddeeeeffffgg..ghhhhhhi",
      "....ihhhhh..ggffffeeeeddddcccbbbbbbbcccdddddeeeeffffggggghhhhhhi",
      "....iihhhh..ggggffffeeeedddccbbbbbbcccccddddeeeefffffgggghhhlhhi",
      "...iiiii......gggffffeeedddccccccccccccdddddeeeefffffgggghhhl...",
      "....iiiii.....ggggfffeeddddccccccccccdddddddeeeeeffffgggghhh....",
      ".....iiiiiiiihhgggffeeedddddddccdccccddddddeeeeefffffggggghh..hi",
      "....iiiiiiiiihhggfffeeeeddddddddddddddddeeeeeeeefffffggggghh..hh",
      "....iiiiiiiiiigggfffeeeedddeedddddddddddeeeeefffffffggggghhlhhhh",
      "...iiiiiiiiiihgggfffeeeeeeeeeeddeddddddeeeeffffffffgggggghhlhhhh",
      "...iiiiiiiiiihgg.ffffeeeeefeeeeeeeeeeeeeeeefffffggggggggh.hhhhhi",
      "...iiiiiiiiihhgg.fffffeeffffeeeeeeeeeeeeeeffffgggggggggh..hhhhhi",
      "....iiiiiii.ihggggfffffffffffeefffeeeeeeeffffgggggghhh....hh..ii",
      ".....iiiii..hhggggfffff.gggffffffffffffffffffgiighhhhh....hh..ii",
      ".....gg.ih..hiiiiigggggggggfffffgffffffffffffiiiiihhhjjjjjiiii..",
      ".....i..lh..iiiiiiiigghhhgggffgggggfffff..ffgiiiiiiijjjjjjjiii..",
      ".....iii..hhiiiiiiiii.hhhhgg..ggggggggggggggiiiiiiiijjjjjjjiii..",
      ".....iii..hiiiiiiiiii.hhhhgg..gghhggggggggggiiiiiiiiijjjjji.....",
      ".....iiiiiihiiiiiiiiii..hh..gg....hhgg..ggggiiiiiiiiiiij.j......",
      "......iiiiiiiiiiiiiiii..hh..hh....hhhh..hhhhiiiiiiiiiiii........",
      "......ii..iiiiiiiiiiiiiiih..hh..hhhhhh..hhhhiiiiiiiiii..........",
      ".......i..iggiiiii....iiih..hh..iiihhh..hhhhiiiiiii.ii..........",
      ".......iii.ggi..............hiii..ii..hhhhhhhiiiiiii..ii........",
      "........ii..i........ii.i...iiii..ii..iiiiiiiiii..ii..ii........",
      "....................iiiiii..iiiii.......iiii..ii..iiiii.........",
      "...................iiiiiii.iiiiii.......iiii..ii..iiii..........",
      "...................iiiiiiiiiiiiiii......iiii..i.................",
      "..................iiiiiiiiiiiiiiii..............................",
      "..................iiiiiiiiiiilliii..............................",
      "..................iiiiiiiiiiiiiiii..............................",
      "...................iiiiii...iiiiii..............................",
      "....................iiii.....iii................................",
      "................................................................",
      "................................................................",
    ],
  },
  boom_4: {
    w: 64, h: 64,
    palette: 'boom',
    pixels: [
      "................jjjj....jjjjjjjj....jjjj..jj....................",
      "..............jjjjjj..iiiiijjjjj....jjjj..jj......j.............",
      "............jj....jjjiiiiiii....jjjjjjjjjj..jjjjjjjj............",
      "..........jjjj....jjjjiiiiiii...jjjjjjjjjj..jjjjjjjj............",
      "......jj..jj....jj..jiiiiiiiiii.ij..jj..jj..jjjjjjjjjj..........",
      "......jj..jj....jj..jiiiiiiiiii.ii..ii.iiiiijjjjjjjjjj..j.......",
      "......jj..........jjiiiiiiiiiiii..iiiiiiiiiijj..jj....jjjjj.....",
      "......jj..........jjiiiiiiiiiiii..iiiiiiiiiiij..jj....jjjjjj....",
      "....jj....jjjj....jiiiiiiiiiiiii..iiiiiiiiiiiijj..jjjjjjjjjjjj..",
      "...jjj....jjjj....iiiiiiiiiiiiii..iiiiiiiiiiiiij..jjjjjjjjjjjjj.",
      "...jjj..jjjj..iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii...jj..jjjjjj..jjj.",
      "..jjjj..jjjj..iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii...ii..jjjjjj..jjj.",
      ".jjjjjjj........iiii..iiiiihhhhhhi..iiiiiiiiii..iiiijj..jjjjjj..",
      "jjjjjjjj........iiii..iiiihhhhhhhh..hhiiiiiiii..iiiiii..jjjjjj..",
      "..jjjjjjjj....ii...iiiiihhhhhhhhhhhhhhhhhiiiii....ii..ij......jj",
      "..jjjjjjij....iiiiiiiiihhhhhhhhhhhhhhhhhhhiiii....ii..ii......jj",
      "..jjjjiiiiiiiiiiiiiihhhhhhhhhhhhhhhh..hhhhhiii..ii....iijjjj....",
      "..jjjiiiiiiiiiiiiihhhhhhhhhhhhhhhhhh..hhhhhhhi..ii....iijjjj....",
      "jj..jjiiiiiiiiiiiiihhhhhhhhhhghhhhhhhhhhhhhhhhhiii..ii....jjjjjj",
      "jj..jjiiiiiiiiiiiiiihhhhhhhgggggggggghhhhhhhhhhhiii.ii....jjjjjj",
      "jj..jjiiiiiiiiiiiiiiihhhhhgggggggggggghhhh..hh..hii.ii..jjjjjjj.",
      "jj..jjiiiiiiiiiiiiiiiihhggggggggggggggghhh..hh..hii.ii..jjjjjjj.",
      "..jjjjiiiiiiiiiiiiiiiiggggggggggggggggggghhhhhhhhiiiiiii....jj..",
      "..jjjjiiiiiiiiiiiiiiiigggggggffffffgggggggghhhhhhiiiiiii....jj..",
      "jj..jjiiiiiiiiiiiiiiigggggggffffffffggggggghhhhhhiii......jjjj..",
      "jj..jjiiiiiiiiiiiiiiigggggffffffffffffggggghhhhhhiii....jjjjj...",
      "..jj..iiiiiiiiiiiiiigggggffffffffffffffgggghhhhhhiiiiiijjjjjj...",
      "..jj..jiiiiiiiihiiiiggggffffffffffffffffggghhhhhiiiiiijjjjjjjj..",
      "....jj....iiiihhhhiiggggfffffeeeeeffffffggghhhhhi.ii..jjjjjjjj..",
      "....jj....iiiihhhhhhggggffffeeeeeeeefffgggghhhhi..ii..jjjjjjjj..",
      ".jjjjj..ii..iiihhhhhggggffffeeeeeeeefffggghhhhiiii..jjjjjjjjjj..",
      "..jjjj..ji..iiihhhhhhgggffffeeeeeeefffggghhhhhiiii..jjjjjjjjjj..",
      "...jjjjjjj..ii..ihhhhhgggffffeeeeeefffggghhhhhiiiiijjjjjjjjjj...",
      "....jjjjjj..ii..iihhhhhgggfffeeeeeefffggghhhhiiiiiijijjjjjjj....",
      ".....jjjjj..ii..iihhhhhgggffffeeeeffffgghh..hiiiiijiijijjjji....",
      "......jjjj..ji..iihhhhhggggffffeeeffffgghh..iiiiiijiiiiiijii....",
      "..........jjji......hhhgggggfffffffffgggghhhiiiiiiiiiiiiiiiii...",
      "..........jjji......hhhhhggggfffffffggggghhhiiiiiiiiiiiiiiiiii..",
      ".......j....iiiiiihh..hhhhgggfffffffgggghhhhiiiiiiiiiiiijiiiii..",
      ".......j....iiiiiiih..hh.hggggfffffgggghhhhiiiiiiiiiiijjjjjji...",
      "......jjjj..ii....iiii..hhhggggggffggghhhhhiiiiiiiiiiijjjjjjj...",
      "....iiiiiii.ii....iiii..hhhhgggggggggghhhhhiiiiiiiiiijjjjjjjj...",
      "...iiiiiiiij......iiiiihhh.hgggggggggghhhhiiiiiiiiiiijjjjjjjj...",
      "...iiiiiiiii......iiiiiihh..hgggggggghhhhhiiiiiiiiiiijjjjjjjj...",
      "..iiiiiiiiiijjjj..iiiiiihhhhhhhhhgggghhihhiiiiiiiiiiiijjjjjjj...",
      "..iiiijjjiiiijjj..iiii.iihhh.hhhhhhiiiiiiii..iiiiiiiiijjjjjj....",
      "..iiijjjjjiiij..jj..iiiiiihhhh....iiiiiiiii..iiiiiiiiijj.jj.....",
      "..iiijjjjjiijj..jj..iiiiiihhhh...iiiiiiiiiii.iiijjjii.jj........",
      "...ijjjjjjii.j.j..jjii...iihhh..hiiiiiiiiiiiiijjiijjjjj.........",
      "....ijjjjjijjjjjj.jjji....ihhh..hiiiiiiiiiiiiiiiiiijjj..........",
      ".....jjjj.jjjjjjj...jj....iiihhhhiiiiiiiiiiiiiiiiiiij...........",
      ".......jjjjjjjjjjj..jj....iiiiiiiiiiiiiiiiiiiiiiiiii............",
      "........jjjjjjjjjj..jj..iiii....iiiiiiiiiiiiiiiiiiii............",
      "........jjjjjjjjjj..jj..iiii....iiiiiiiiiiiiiiiiiiii............",
      ".........jjjjjjjjj..jj......ii..ii..iiiiiiiiiiiiiiii............",
      ".........jjjjjjj....jj......ii..ijj.iiiiiiiiiiiiiii.............",
      "..........jjjjj.........jiii..ijjjjjiiiiiiiiiiiiiii.............",
      "........................jjii..ijjjjjjiiiiiiiiiiiiii.............",
      "....................jjjjjjjj..jjjjjjjiiiiiiiiiiiii..............",
      ".....................jjjjjjj..jjjjjjjiiiiiiiii..................",
      "........................jjjjjjjjjjjjjiiiiiiii...................",
      "........................jjjjjjjjjjjj.iiiiiiii...................",
      "......................jj..jj....jjjjjjijiiiiij..................",
      "......................jj..jj....jjjjjjjjjjjjjj..................",
    ],
  },
  boom_5: {
    w: 64, h: 64,
    palette: 'boom',
    pixels: [
      ".............................jjjj...............................",
      "........................ii..jjjjjjj.............................",
      "......................ii......jjjj....hh..hh....................",
      ".....................iii......jjjj....hh..hhh...................",
      ".....................i..iiiijjjjjjjjjh..........................",
      "....................ii..iiiijjjjjjjjjhhh........................",
      "....................iiiiiiiijjjj..jj........hh..................",
      "....................iiiiiiiijjjj..jj........hh..................",
      "....................iiiiiiiiijjjjjjijj..jjhhjjjjjh..............",
      "....................iiiiiiiii.ijiiiiij..jjjhjjjjjjh.............",
      ".....jjjjj..........iiiiiiiiii..iiiiijjj....jjjjjj..ii..........",
      "....jjjjjj..ihhhhh..iiiiiiiiii..iiiiijjj...jjjjjjj..ii..i.......",
      "...jjjjjjj........iiiiiiiiii..iiii..i.jj....jjjj..ji....i.......",
      "...jjjjjjj....i...iiiiiiiiii...iii....jj....jjjj..ii....ii......",
      "...jjjjjjj..jjih..hiiiiiiiiii...iiiiii....jj.jjjjjiiiiiiii......",
      "....jjjjjj..jjii..iiiiiiiiii....iiiiii....jj..jjh.iiiiiiii......",
      ".....jjjjjjjjiii....ii..iiiiiiii..ii..iiii....jjhhii..iiii......",
      ".....jjjjjjjjiii....ii..iiiiii....ii..iiii....jjjhhi..iii.......",
      ".....j.jjjjjii..ii..jjjj..............iiii....jj...iii..hhh.....",
      "..........hhii..ii..iiii................ii....jj........hhhh....",
      "........hh......iii.....iiii..........ii..iijj..jjjh............",
      "........hh......iii.....iii...............iiij..jjjj............",
      "..........hh..jjjjiiii....................ii..jjjj............hh",
      "..........hj..jjjiiiii....................ii..ijjj............hh",
      "......hh..hj......i......................i.i....ii....jj........",
      "......hh..jj......i......................i......ii....jj........",
      ".........h..jj..iiii..........................ii......jjjjjhhh..",
      "........hh..jj..iiii..........................ii......jjjjjhhh..",
      "....hhhhhj....ji.i............................iiii..ijjj......hh",
      "....hhhhhh....ji.i............................iiii..ijjj......hh",
      "..........jj..jiii............................iiiiii............",
      "..........hj..jjii............................iiiiii............",
      "......hh......jjji............................iiii..ijjj..jhhh..",
      ".......h......jjjj............................iiii..jjjj..jhhh..",
      "........hh..hjjj.............................i...iiii.jj..jhhhhh",
      "........hh..hjjj............................ii..iiiiiiij..hhhhhh",
      "...........................................iiiii..ii..iijhhhhh..",
      "..........................................iiiiii..ii..iihhhhhh..",
      ".........h..iii................................iii..iiii..hhhh..",
      ".........iiiiiii...............................iii..iii...hh....",
      ".........iii..iiij..ii...................i..jj.iiiii..ih........",
      "........iiii..iiij..ii..................ii..jj.iiiii..i.........",
      ".........i..iiiii...ii..................iijjjjjjiiii..ih........",
      ".........i..iiii....ii..................iijjjjjhiiii..h.........",
      ".........iiiiiiijiiiiiii..........iiii..jj....jhhiihhh..........",
      "...........iiiijjiiiiiii..........iijj..jj....hhhhhh............",
      ".........h....jjjiiiiiii........ii..jjjj....jjh.hhh.............",
      ".........h..jjjjjijiiiii........ij..j.jj....jhjjjh..............",
      "..........hh.jjj..jiii............jj.i....hhhhjjjjjj............",
      "..........hjjjjj..jiii............jjii....hhhjjjjjjj............",
      "...........jjjjjjjjjii..iiiiiijj..jjiiiiii..jjjj..jjj...........",
      "...........jjjjjjjjjii..iiiijjjj..jiiiiiii...jjj..jj............",
      "........hh.j..jj..jjiiii..jj....jjhiii..ii....jjjjjj............",
      "........hh.j..jj..jiiiii..jj....jhhiii..ii....jjjjj.............",
      "........hh......jjiii...jj..........iiiiii....jjjjj.............",
      "........hh........iii...jj..........iiiiii......jj..............",
      "........hh....hh..hj..jjjj....hh..hh....i.......................",
      ".........h....hh..hh..jjjj....hh..h.............................",
      ".........hhh..hh..hhhh..jjhhhh..h...............................",
      "...........h..hh..hhhh..hhhhhh..................................",
      "......................hh........................................",
      "......................hh........................................",
      "..................hhhh..........................................",
      "..................hhhh..........................................",
    ],
  },
  flash_0: {
    w: 20, h: 20,
    palette: 'flash',
    pixels: [
      "....................",
      "....................",
      "....................",
      "....................",
      "....................",
      "....................",
      "....................",
      ".....dcccdd.........",
      "...dbbbbccdd........",
      "...aaabbbcccdd......",
      "...aaabbbcccdd......",
      "....bbbbccdd........",
      ".....cccccd.........",
      ".......ddddd........",
      "....................",
      "....................",
      "....................",
      "....................",
      "....................",
      "....................",
    ],
  },
  flash_1: {
    w: 20, h: 20,
    palette: 'flash',
    pixels: [
      "....................",
      "...........e..e.....",
      ".........ddddeee....",
      "........ddddddde.ee.",
      ".......ccccddddddeee",
      ".....dcccccccdddddee",
      "....dcbbccccccddddee",
      "...ebbbbbbcccccdddde",
      "...baabbbbcccccdddde",
      "...aaaabbbbccccdddde",
      "...aaaabbbbcccccddde",
      "...baaabbbbbccccdddd",
      "...ebbbbbbbccccccddd",
      "....dcccccccccccdddd",
      ".....ecccccccccddddd",
      ".......dddddddddddde",
      "........edddeedddee.",
      "..........eeee.ee.e.",
      "....................",
      "....................",
    ],
  },
  flash_2: {
    w: 20, h: 20,
    palette: 'flash',
    pixels: [
      "....................",
      "....................",
      "..............ff....",
      "...........f..ff....",
      "........e..e.e......",
      "......e.d..d.e......",
      "....fd.d...d..dde..e",
      "....dc.c...d..ddd..e",
      ".....ccc.cccdddd.de.",
      "...b.bbc.cccdddd.de.",
      ".....bccccc.....dee.",
      ".....ccccdd.....eee.",
      "....dcc.d.d..e......",
      ".....e..d.d..e......",
      ".......edd.e..e..f..",
      ".........e.e..f..f..",
      "............ee.ff...",
      "............ff.f....",
      "...............f....",
      "....................",
    ],
  },
  chip_0: {
    w: 4, h: 4,
    palette: 'chip',
    pixels: [
      "..a.",
      ".acb",
      "acbb",
      ".aa.",
    ],
  },
  chip_1: {
    w: 3, h: 3,
    palette: 'chip',
    pixels: [
      "aa.",
      "acb",
      ".ab",
    ],
  },
  chip_2: {
    w: 5, h: 5,
    palette: 'chip',
    pixels: [
      "..a..",
      ".acb.",
      "acbba",
      ".abb.",
      "..a..",
    ],
  },
};
